// Generates src/book-data.ts from the extracted book text.
// Splits into chapters on the "N Title" heading immediately followed by a
// "DOI: 10.4324/9781003665373-..." line (the reliable per-chapter marker).
// Produces verbatim chapter text. Shared with the author's permission (2026-06-23); CC BY-NC-ND 4.0.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// Regeneration only (the text is already committed in src/book-data.ts). Point this at a
// local copy of the Open Access book text, via DWP_SOURCE_TXT or ./source/<file>.txt.
const SRC = process.env.DWP_SOURCE_TXT || path.join(__dirname, "..", "source", "democracy-without-politicians.txt");
const OUT = path.join(__dirname, "..", "src", "book-data.ts");

const raw = fs.readFileSync(SRC, "utf8");
const lines = raw.split(/\r?\n/);

const headRe = /^(\d{1,2})\s+([^\d].*\S)$/;
const doiRe = /^DOI: 10\.4324\/9781003665373-/;
const noticeRe = /CC-BY-NC-ND license/;

function doiWithin(i) {
  for (let k = i + 1; k < Math.min(lines.length, i + 5); k++) {
    if (doiRe.test(lines[k].trim())) return k;
  }
  return -1;
}

const markers = [];
for (let i = 0; i < lines.length; i++) {
  const h = headRe.exec(lines[i].trim());
  if (!h) continue;
  const doiIdx = doiWithin(i);
  if (doiIdx === -1) continue;
  let bodyStart = doiIdx + 1;
  for (let k = doiIdx + 1; k < Math.min(lines.length, doiIdx + 4); k++) {
    if (noticeRe.test(lines[k])) { bodyStart = k + 1; break; }
  }
  markers.push({ headIndex: i, number: parseInt(h[1], 10), title: h[2].trim(), bodyStart });
}

// De-dupe accidental double-detects; keep ascending order.
markers.sort((a, b) => a.headIndex - b.headIndex);

const chapters = [];
for (let m = 0; m < markers.length; m++) {
  const start = markers[m].bodyStart;
  const end = m + 1 < markers.length ? markers[m + 1].headIndex : lines.length;
  let body = lines.slice(start, end).join("\n");
  body = body
    .replace(new RegExp(".*CC-BY-NC-ND license.*\\n?", "g"), "")
    .replace(/^DOI: 10\.4324.*$/gm, "")
    .replace(/[ \t]+/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
  chapters.push({ number: markers[m].number, title: markers[m].title, text: body });
}

const header = `// AUTO-GENERATED by scripts/gen-data.mjs — do not edit by hand.
// Source: Terry Bouricius, "Democracy Without Politicians" (Routledge, 2026), CC BY-NC-ND 4.0.
// Shared with the author's permission (2026-06-23): verbatim passages only, not AI summaries. Attribute Terry Bouricius (CC BY-NC-ND 4.0).
export interface RawChapter { number: number; title: string; text: string; }
export const CHAPTERS: RawChapter[] = ${JSON.stringify(chapters, null, 0)};
`;

fs.writeFileSync(OUT, header, "utf8");
const words = chapters.reduce((n, c) => n + c.text.split(/\s+/).length, 0);
console.log(`Wrote ${OUT}`);
console.log(`Chapters: ${chapters.length} | total words: ~${words}`);
console.log(chapters.map((c) => `  ${c.number}. ${c.title} (${c.text.split(/\s+/).length} words)`).join("\n"));
